sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es4c
sonar.projectName=yovi_es4c

sonar.sources=webapp/src,users,gamey/src,gateway/src/main,auth-service
sonar.tests=webapp/src,users/__tests__,gamey/src,gateway/src/test, auth-service/__tests__
sonar.test.inclusions=**/*.test.tsx,**/*.test.js,**/*Test.java
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info
sonar.java.coveragePlugin=jacoco
sonar.java.binaries=gateway/target/classes
sonar.coverage.jacoco.xmlReportPaths=gateway/target/site/jacoco/jacoco.xml
