server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Para que React Router funcione correctamente
    location / {
        try_files $uri $uri/ /index.html;
    }
}